import = [ "~/.config/alacritty/theme/nightify.toml"]


[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.italic]
family = "Dank Mono"
style = "Italic"

[font.offset]
y = 0

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
opacity = 0.95
title = ""
decorations = "None"

[window.padding]
x = 16
y = 14

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
