

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
# family = "Dank Mono"
family = "Hack Nerd Font Mono"
# family = "JetbrainsMono NF"
# family = "Operator Mono Medium"
style = "Reguler"

[font.italic]
# family = "JetbrainsMono NF"
family = "Operator Mono"
style = "Italic"

[font.offset]
y = 1

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
opacity = 0.95
title = ""
decorations = "None"

[window.padding]
x = 16
y = 14

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [ "~/.config/alacritty/theme/catppuccino.toml"]

[terminal]
